struc.complex1 <- read.csv("~/git/coralscape_open3d/results/sample_metadata_cur_kal_05m_20200214_decvis_02.ply.csv")
struc.complex2 <- read.csv("~/git/coralscape_open3d/results/sample_metadata_cur_kal_10m_20200214_decvis_02.ply.csv")
struc.complex3 <- read.csv("~/git/coralscape_open3d/results/sample_metadata_cur_kal_20m_20200214_decvis_02.ply.csv")
struc.complex4 <- read.csv("~/git/coralscape_open3d/results/sample_metadata_cur_sna_10m_20200303_decvis_02.ply.csv")
struc.complex5 <- read.csv("~/git/coralscape_open3d/results/sample_metadata_cur_sna_20m_20200303_decvis_02.ply.csv")
struc.complex6 <- read.csv("~/git/coralscape_open3d/results/sample_metadata_cur_sna_05m_20200303_decvis_02.ply.csv")
struc.complex <- rbind(struc.complex1,struc.complex2,struc.complex3,struc.complex4,struc.complex5,struc.complex6)
write.csv(struc.complex, file = "~/git/coralscape_open3d/results/sample_metadata.csv", quote = FALSE, row.names = FALSE)

annotations1 <- read.csv("~/git/coralscape_open3d/results/scaled_annotations_cur_kal_05m_20200214_decvis_02.ply.csv")
annotations2 <- read.csv("~/git/coralscape_open3d/results/scaled_annotations_cur_kal_10m_20200214_decvis_02.ply.csv")
annotations3 <- read.csv("~/git/coralscape_open3d/results/scaled_annotations_cur_kal_20m_20200214_decvis_02.ply.csv")
annotations4 <- read.csv("~/git/coralscape_open3d/results/scaled_annotations_cur_sna_10m_20200303_decvis_02.ply.csv")
annotations5 <- read.csv("~/git/coralscape_open3d/results/scaled_annotations_cur_sna_20m_20200303_decvis_02.ply.csv")
annotations6 <- read.csv("~/git/coralscape_open3d/results/scaled_annotations_cur_sna_05m_20200303_decvis_02.ply.csv")
annotations <- rbind(annotations1,annotations2, annotations3, annotations4, annotations5, annotations6)
write.csv(annotations, file = "~/git/coralscape_open3d/results/annotations.csv", quote = FALSE, row.names = FALSE)
